<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
    <!-- E ouvi o anjo das águas, que dizia: Justo és tu, ó Senhor, que és, e que eras, e santo és, porque julgaste estas coisas.  -->
        <meta charset="utf-8">

        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = 'Sara Nossa Terra';
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ;
        ?>
    </head>
    <body>
        <div class="container">
        
            <div class="header">
                
                <h3 class="text-muted"><img  alt="140x140" src="/public/img/snt.png" /></h3>
            </div>
            <hr>
            <?php echo $this->message(); ?>

            <div class="row marketing">
                <?php echo $this->content; ?>
            </div>

            <div class="footer">
                <p class="muted credit pull-left">Sara Nossa Terra (beta) <a href="">© 2014</a></p>
                <p class="muted credit pull-right">Desenvolvido por <a href="#">ArmazemDev</a>.</p>
            </div>
        </div>

        <!-- Scripts -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/scripts.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
                ->prependFile($this->basePath() . '/js/jquery.maskMoney.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                
        ;

        echo $this->inlineScript();
        ?>
    </body>
</html>