    <?php

		$title = 'Novo Lançamento.';
		$this->headTitle($title);
		?>
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="panel-title">
					Editar o Relatorio com ID: <?php echo $this->id; ?>  
				</div>
			</div>
    
    <?php 
	$form = $this->form;
	$form->setAttribute('action',
			$this->url(
					'culto',
					array(	'controller' => 'CultoController',
							'action' => 'edit',
							'id'     => $this->id,
					)));

	$form->setAttribute('class', 'form-horizontal');
	$form->prepare();

	echo $this->form()->openTag($form);
	?>
	

    				
        <div class="panel-body">
        	<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Culto.</h3>
				</div>
				<div class="panel-body">
                   	<?php echo $this->formRow($form->get('cultoData')); ?>
                    <?php echo $this->formRow($form->get('nomePastor')); ?>
                    <?php echo $this->formRow($form->get('preletor')); ?>
                    <?php echo $this->formRow($form->get('reuniao')); ?>
                    <?php echo $this->formRow($form->get('tema')); ?>
                    <?php echo $this->formRow($form->get('txtBiblico')); ?>
                    <?php echo $this->formRow($form->get('numPessoas')); ?>
                    <?php echo $this->formRow($form->get('numLideres')); ?>
                    <?php echo $this->formRow($form->get('numConsolid')); ?>
            	</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Dízimos.</h3>
				</div>
				<div class="panel-body">
                    <?php echo $this->formRow($form->get('dnhDizimos')); ?>
                    <?php echo $this->formRow($form->get('chqDizimos')); ?>
                    <?php echo $this->formRow($form->get('moeDizimos')); ?>
                    </div>

			</div>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Ofertas.</h3>
				</div>
				<div class="panel-body">
                    <?php echo $this->formRow($form->get('dnhOfertas')); ?>
                    <?php echo $this->formRow($form->get('chqOfertas')); ?>
                    <?php echo $this->formRow($form->get('moeOfertas')); ?>
                    </div>

			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Parceiro de Deus.</h3>
				</div>
				<div class="panel-body">
                    <?php echo $this->formRow($form->get('dnhParcDeus')); ?>
                    <?php echo $this->formRow($form->get('chqParcDeus')); ?>
                    <?php echo $this->formRow($form->get('moeParcDeus')); ?>
                    </div>
                </div>
                    <?php //echo $this->formRow($form->get('anexos')); ?>
        </div>
        <div class="panel-footer">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <button type="submit" class="btn btn-primary">Atualizar registro.</button>
				
            <a href="<?php echo $this->url('culto'); ?>" class="btn btn-default">Voltar</a>
        </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
</div>
<?php $this->headScript()->captureStart();?>

$(function() { $("#dnhDizimos, #chqDizimos, #moeDizimos, #dnhOfertas, #chqOfertas, #moeOfertas, #dnhParcDeus, #chqParcDeus, #moeParcDeus")
.maskMoney({prefix:'R$ ', allowNegative: true,thousands:'.',
decimal:',', affixesStay: false}); })




<?php $this->headScript()->captureEnd();?>